"""Render bounded chart data and attach the resulting PNG to Zoom chat."""
import html
import json
import math
import re
from contextlib import suppress
from pathlib import Path
from uuid import uuid4


def extract_plot(text):
    match = re.search(r'```plot\s*\n(.*?)```', text, re.S)
    if not match:
        return None
    data = json.loads(match[1])
    if not isinstance(data, dict) or set(data) != {'title', 'unit', 'labels', 'values'}:
        raise ValueError('Invalid plot fields')
    if not all(isinstance(data[k], str) and len(data[k]) <= 160 for k in ('title', 'unit')):
        raise ValueError('Invalid plot title or unit')
    labels, values = data['labels'], data['values']
    if not isinstance(labels, list) or not isinstance(values, list) or not 1 <= len(labels) <= 24 or len(labels) != len(values):
        raise ValueError('Expected 1–24 matching labels and values')
    if any(not isinstance(s, str) or len(s) > 80 for s in labels):
        raise ValueError('Invalid labels')
    if any(type(v) not in (int, float) or not math.isfinite(v) or v < 0 for v in values):
        raise ValueError('Plot requires finite nonnegative values')
    return data


def plot_html(data):
    rows = []
    maximum = max(data['values']) or 1
    for label, value in zip(data['labels'], data['values']):
        rows.append(f'<div class="row"><div>{html.escape(label)}</div>'
                    f'<div class="track"><div class="bar" style="width:{value / maximum * 100:.4f}%"></div></div>'
                    f'<strong>{value:,.2f}</strong></div>')
    return ('<!doctype html><meta charset="utf-8"><style>'
            'body{margin:0;padding:48px;background:#f5f7fb;color:#15243a;font:18px Arial}'
            'h1{font-size:32px;margin:0 0 12px}p{color:#53647b}'
            '.row{display:grid;grid-template-columns:180px 1fr 150px;align-items:center;gap:18px;margin:22px 0}'
            '.track{background:#e1e7ef;height:30px}.bar{background:#2764d8;height:30px}'
            'strong{text-align:right}footer{font-size:14px;margin-top:36px;color:#53647b}</style>'
            f'<h1>{html.escape(data["title"])}</h1><p>{html.escape(data["unit"])}</p>'
            + ''.join(rows) + '<footer>Generated by Colleague AI from the configured workspace</footer>')


async def create_and_share_plot(page, text, directory):
    try:
        data = extract_plot(text)
        if data is None:
            return None
    except (ValueError, TypeError):
        return {'status': 'failed', 'error': 'Codex returned invalid chart data'}
    directory = Path(directory)
    name = 'plot-' + uuid4().hex[:12] + '.png'
    path = directory / name
    chart_page = await page.context.new_page()
    try:
        await chart_page.set_viewport_size({'width': 1100, 'height': 230 + 54 * len(data['labels'])})
        await chart_page.set_content(plot_html(data))
        await chart_page.screenshot(path=str(path), full_page=True)
    finally:
        await chart_page.close()
    (directory / name.replace('.png', '.json')).write_text(json.dumps(data, indent=2))
    return await share_plot_file(page, path, data['title'])


async def share_plot_file(page, path, title):
    """Attach an existing plot without rerunning the analysis or closing open chat."""
    path = Path(path)
    directory, name = path.parent, path.name
    result = {'status': 'saved_locally', 'file': name, 'title': title}
    step = 'open_chat'
    try:
        await page.bring_to_front()
        if await page.get_by_text('You have been removed', exact=True).is_visible():
            result.update(error='The host removed the agent from the meeting',
                          error_code='removed_from_meeting', failed_step=step)
            return result
        opened = page.get_by_role('button', name='close the chat panel', exact=True)
        if not await opened.count():
            viewport = page.viewport_size or {'width': 1280, 'height': 720}
            await page.mouse.move(viewport['width'] / 2, viewport['height'] - 25)
            chat = page.get_by_role('button', name='open the chat panel', exact=True)
            await chat.click(timeout=4000)
        onboarding = page.get_by_role('button', name='Got it', exact=True)
        if await onboarding.is_visible():
            await onboarding.click(timeout=3000)
        step = 'confirm_recipient'
        # Never send an attachment into a previously selected private conversation.
        everyone = page.get_by_role('button', name=re.compile(
            r'^Send chat to (Everyone|Meeting Group Chat) please select a receiver$', re.I)).first
        if not await everyone.is_visible():
            result['error'] = 'Could not confirm the meeting-wide chat recipient'
            return result
        step = 'open_file_menu'
        file_button = page.get_by_role('button', name=re.compile(r'^(File|Send file|Send a file|Attach file)$', re.I)).first
        if not await file_button.is_visible():
            result['error'] = 'Zoom file transfer is unavailable in this meeting or browser'
            result['failed_step'] = step
            result['error_code'] = 'file_transfer_unavailable'
            return result
        await file_button.click(timeout=4000)
        step = 'choose_local_file'
        computer = page.get_by_text(re.compile(r'^(Your Computer|Your computer|My Computer)$')).first
        async with page.expect_file_chooser(timeout=5000) as chooser:
            await computer.click(timeout=4000)
        await (await chooser.value).set_files(str(path))
        step = 'send_attachment'
        send = page.get_by_role('button', name=re.compile(r'^Send$', re.I)).last
        await send.click(timeout=5000)
        # A click alone is not proof that Zoom delivered the file.
        result['status'] = 'upload_submitted'
        result['note'] = 'Upload submitted; recipient delivery has not been independently confirmed'
    except Exception as exc:
        result['error'] = f'Zoom upload failed at {step}: {type(exc).__name__}'
        result['failed_step'] = step
        with suppress(Exception):
            (directory / name.replace('.png', '-upload.txt')).write_text(await page.locator('body').aria_snapshot())
            await page.screenshot(path=str(directory / name.replace('.png', '-upload.png')))
    return result
